USE tienda;
SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, TRUNCATE(precio*1.2161,2) FROM producto; 
SELECT nombre AS 'nom de producte', precio AS euros, TRUNCATE(precio*1.2161,2) AS dolars FROM producto; 
SELECT UPPER(nombre), precio FROM producto;
SELECT LOWER(nombre), precio FROM producto;
SELECT nombre, UPPER(SUBSTRING(nombre, 1,2)) AS siglas FROM fabricante;
SELECT nombre, ROUND(precio) FROM producto;
SELECT nombre, TRUNCATE(precio,0) FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC; 
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante ORDER BY codigo LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT p.nombre producto, p.precio, f.nombre fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre producto, p.precio, f.nombre fabricante FROM producto p JOIN fabricante f  ON p.codigo_fabricante = f.codigo ORDER BY fabricante ASC;
SELECT p.codigo codigo, p.nombre producto, f.codigo codigo, f.nombre fabricante FROM producto p JOIN fabricante f  ON p.codigo_fabricante = f.codigo;
SELECT p.nombre producto, p.precio, f.nombre fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY precio ASC LIMIT 1;
SELECT p.nombre producto, p.precio, f.nombre fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY precio DESC LIMIT 1;
SELECT * FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'Lenovo';
SELECT * FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'Crucial' AND p.precio > 200;
